#!/usr/bin/env ruby

require "snowflakey"

prefix = ARGV[0].to_s.gsub(/[[:space:]]/, "")
size   = ARGV[1].to_i

if prefix == ""
  prefix = nil
end

if size.zero?
  size = 96
end

puts Snowflakey.generate(prefix, size: size)
